[package]
name = "Advent2019"
version = "0.1.0"
authors = ["Kevin Murray <kevin.murray@omnihotels.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
